// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:8126979e-a739-4b14-99df-fe756ecebf88",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_l9Y7dFUDD",
    "aws_user_pools_web_client_id": "vhl0uoaqb9mthjjtltgstahtn",
    "oauth": {},
    "federationTarget": "COGNITO_IDENTITY_POOLS",
    "aws_appsync_graphqlEndpoint": "https://g3uvz3crsze6vfxxwsgdqpgpee.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_mobile_analytics_app_id": "b11dffbd151f457d8932a90851c25e70",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
